[platformio]
default_envs = esp32dev
src_dir = src

[env:esp32dev]
platform = platformio/espressif32
framework = espidf
board = esp32dev
; Set this to the real COM port for your ESP32 on Windows, for example:
; upload_port = COM3
; monitor_port = COM3
monitor_speed = 115200
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="sdkconfig.defaults"
build_flags =
    -Wno-unused-function
    -Wno-unused-variable
